var x = 10;
console.log(x);
var s = "Hello TypeScript";
console.log(s);
var arr = ["AngularJS", "ReactJS", "NodeJS"];
console.log(arr.length);
console.log(arr);
console.log(arr[0]);
var arr1 = ["AngularJS", 123, true];
console.log(arr1.length);
console.log(arr1);
console.log(arr1[2]);
